Refactoring of FT configurations for publishing them divided per part
icub-tech-iit/ergocub-software pull request #123
Opened 2023-05-30 13:56 UTC by martinaxgloria

With this PR, the simulated configurations should publish FT data divided per part, aligned with the changes made in robots-configuration.

2023-05-30 14:09 UTC, Nicogene requested changes
Seems ok thanks!

I would also change the configuration files related to wbd, such as:

- https://github.com/icub-tech-iit/ergocub-software/blob/master/urdf/ergoCub/conf/estimators/wbd_ecub_sim.xml
- https://github.com/icub-tech-iit/ergocub-software/blob/master/urdf/ergoCub/conf/launch_wholebodydynamics_ecub.xml


(maybe you can add it in the `simmechanics` folder and then edit there)

2023-05-30 14:45 UTC, Nicogene approved these changes

2023-05-30 14:46 UTC, Nicogene commented
Seems ok to me, putting also @traversaro in the loop

2023-06-05 10:14 UTC, martinaxgloria commented
With this https://github.com/icub-tech-iit/ergocub-software/pull/123/commits/6d73712b9372bf5050ce21de568d750fd9869866, we are able to see the opened ports related to the FT sensors measurements from left/right arm and leg, as you can see in the log below:
```
martinagloria@IITICUBLAP190 ~ $ yarp name list
registration name /ergocubSim/depthCamera/depthImage:o ip 192.168.25.156 port 10028 type tcp
registration name /ergocubSim/depthCamera/rgbImage:o ip 192.168.25.156 port 10027 type tcp
registration name /ergocubSim/depthCamera/rpc:i ip 192.168.25.156 port 10026 type tcp
registration name /ergocubSim/head/command:i ip 192.168.25.156 port 10019 type tcp
registration name /ergocubSim/head/inertials/measures:o ip 192.168.25.156 port 10043 type tcp
registration name /ergocubSim/head/inertials/rpc:o ip 192.168.25.156 port 10044 type tcp
registration name /ergocubSim/head/rpc:i ip 192.168.25.156 port 10018 type tcp
registration name /ergocubSim/head/state:o ip 192.168.25.156 port 10020 type tcp
registration name /ergocubSim/head/stateExt:o ip 192.168.25.156 port 10021 type tcp
registration name /ergocubSim/laser:o ip 192.168.25.156 port 10029 type tcp
registration name /ergocubSim/laser:o/rpc:i ip 192.168.25.156 port 10030 type tcp
registration name /ergocubSim/left_arm/FT/measures:o ip 192.168.25.156 port 10051 type tcp
registration name /ergocubSim/left_arm/FT/rpc:o ip 192.168.25.156 port 10052 type tcp
registration name /ergocubSim/left_arm/command:i ip 192.168.25.156 port 10003 type tcp
registration name /ergocubSim/left_arm/rpc:i ip 192.168.25.156 port 10002 type tcp
registration name /ergocubSim/left_arm/state:o ip 192.168.25.156 port 10004 type tcp
registration name /ergocubSim/left_arm/stateExt:o ip 192.168.25.156 port 10005 type tcp
registration name /ergocubSim/left_leg/FT/measures:o ip 192.168.25.156 port 10047 type tcp
registration name /ergocubSim/left_leg/FT/rpc:o ip 192.168.25.156 port 10048 type tcp
registration name /ergocubSim/left_leg/command:i ip 192.168.25.156 port 10011 type tcp
registration name /ergocubSim/left_leg/rpc:i ip 192.168.25.156 port 10010 type tcp
registration name /ergocubSim/left_leg/state:o ip 192.168.25.156 port 10012 type tcp
registration name /ergocubSim/left_leg/stateExt:o ip 192.168.25.156 port 10013 type tcp
registration name /ergocubSim/right_arm/FT/measures:o ip 192.168.25.156 port 10053 type tcp
registration name /ergocubSim/right_arm/FT/rpc:o ip 192.168.25.156 port 10054 type tcp
registration name /ergocubSim/right_arm/command:i ip 192.168.25.156 port 10007 type tcp
registration name /ergocubSim/right_arm/rpc:i ip 192.168.25.156 port 10006 type tcp
registration name /ergocubSim/right_arm/state:o ip 192.168.25.156 port 10008 type tcp
registration name /ergocubSim/right_arm/stateExt:o ip 192.168.25.156 port 10009 type tcp
registration name /ergocubSim/right_leg/FT/measures:o ip 192.168.25.156 port 10049 type tcp
registration name /ergocubSim/right_leg/FT/rpc:o ip 192.168.25.156 port 10050 type tcp
registration name /ergocubSim/right_leg/command:i ip 192.168.25.156 port 10015 type tcp
registration name /ergocubSim/right_leg/rpc:i ip 192.168.25.156 port 10014 type tcp
registration name /ergocubSim/right_leg/state:o ip 192.168.25.156 port 10016 type tcp
registration name /ergocubSim/right_leg/stateExt:o ip 192.168.25.156 port 10017 type tcp
registration name /ergocubSim/torso/command:i ip 192.168.25.156 port 10023 type tcp
registration name /ergocubSim/torso/rpc:i ip 192.168.25.156 port 10022 type tcp
registration name /ergocubSim/torso/state:o ip 192.168.25.156 port 10024 type tcp
registration name /ergocubSim/torso/stateExt:o ip 192.168.25.156 port 10025 type tcp
registration name /ergocubSim/waist/inertials/measures:o ip 192.168.25.156 port 10045 type tcp
registration name /ergocubSim/waist/inertials/rpc:o ip 192.168.25.156 port 10046 type tcp
registration name /root ip 192.168.25.156 port 10000 type tcp
registration name /tmp/port/1 ip 192.168.25.156 port 10055 type tcp
registration name fallback ip 224.2.1.1 port 10000 type mcast
*** end of message
```

cc @Nicogene @traversaro

2023-06-05 12:49 UTC, traversaro approved these changes

2023-06-05 12:53 UTC, merged