Change hands configuration files
icub-tech-iit/ergocub-software pull request #169
Opened 2023-09-11 10:05 UTC by Nicogene

It requires https://github.com/robotology/gazebo-yarp-plugins/pull/662

2023-09-11 11:02 UTC, xEnVrE requested changes
Thanks @Nicogene, I am requesting changes as some of the numbers are not correct as per the documentation.

Moreover, the limits for the new hand in https://github.com/icub-tech-iit/ergocub-software/blob/5ca85d3b065f47ea652bb413d9b0536f5dfcc72c/urdf/creo2urdf/data/ergocub1_1/ERGOCUB_joint_all_parameters.csv seems not updated as in the documentation https://icub-tech-iit.github.io/documentation/hands/hands_mk5/

2023-09-11 12:18 UTC, xEnVrE commented on urdf/ergoCub/conf/gazebo_ergocub_left_hand_mk5_1.ini
> +b        0.00652  0.0055  0.0055  0.0055   0.0055
See https://github.com/icub-tech-iit/documentation/issues/307

2023-09-11 12:19 UTC, xEnVrE commented on urdf/ergoCub/conf/gazebo_ergocub_right_hand_mk5_1.ini
> +b        0.00652  0.0055  0.0055  0.0055   0.0055
https://github.com/icub-tech-iit/documentation/issues/307

2023-09-11 12:21 UTC, xEnVrE commented on urdf/ergoCub/conf/gazebo_ergocub_right_hand_mk5_1.ini
> +q2bias    173.35  173.35  173.35  173.35  -170.54
As per https://icub-tech-iit.github.io/documentation/hands/hands_mk5_coupling/#mk51-coupling-variables

2023-09-12 12:28 UTC, Nicogene commented
@xEnVrE I updated the limits for the hand mk5.1 also in the csv/urdf and I corrected the coupling params as done here:

https://github.com/icub-tech-iit/documentation/pull/312

I think we can safely merge

2023-09-12 12:43 UTC, xEnVrE approved these changes

2023-09-12 12:44 UTC, merged