Updated livescript for PID fingers tuning and related scripts
icub-tech-iit/ergocub-software pull request #247
Opened 2024-05-15 09:34 UTC by simeonedussoni

in this PR some improvements are implemented, the most important:
- interactive choice of the data files for calibration
- save of the report in dedicated file with speaking name together with `.m` dataset
- script to reset workspace

2024-05-15 12:49 UTC, pattacini requested changes
Some inline comments to address.

2024-05-15 12:49 UTC, pattacini commented on src/tools/ergocub-fingers-tuning/init_ws.m
Missing Copyright

2024-05-15 12:49 UTC, pattacini commented on src/tools/ergocub-fingers-tuning/results/middle6-cus_PID - Copy.pdf
Strage name for the file. Better off repurposing or simply delete it if it's a leftover.

2024-05-15 12:49 UTC, pattacini commented on src/tools/ergocub-fingers-tuning/results/middle7-cus_PID - Copy.pdf
Same as above.

2024-05-15 12:49 UTC, pattacini commented on src/tools/ergocub-fingers-tuning/results/rinky2-cus_PID - Copy.pdf
Same as above.

2024-05-15 12:49 UTC, pattacini commented on src/tools/ergocub-fingers-tuning/results/rinky3-cus_PID - Copy.pdf
Same as above.

2024-05-15 12:49 UTC, pattacini commented on src/tools/ergocub-fingers-tuning/scripts/design_robust_pid.m
> +        disp('scegli PI o PID')
No Italian, please.

2024-05-15 12:49 UTC, pattacini commented on src/tools/ergocub-fingers-tuning/scripts/Reshape_dataset.m
> +        interpola (1,1) {mustBeInteger}
No Italian, please.

2024-05-15 12:49 UTC, pattacini commented on src/tools/ergocub-fingers-tuning/README.md
> +   - it's better to also 'clear all output' by right-clicking in the livescript otherwise the report can be filled with old data and plots!
It seems there's a typo.

2024-05-15 12:49 UTC, pattacini commented on src/tools/ergocub-fingers-tuning/README.md
> +   - sometimes (very often) the final command 'export' doesn't produce a complete pdf file. re-run this line by selecting it until the pdf looks fine
Uhm 🤔
This should be fixed upfront. Fine for now, but then the root cause ought to be sorted out.

2024-05-15 13:48 UTC, pattacini requested changes
Some more hints.

I'll leave the review of the live script to @mfussi66.

2024-05-15 13:48 UTC, pattacini commented on src/tools/ergocub-fingers-tuning/README.md
> +5. check the plots: anytime the fingers are not moving, the PID parameters are screwed up see e.g. [here](https://github.com/icub-tech-iit/ergocub-design-lowerarm/issues/245#issuecomment-2095469706)
```suggestion
5. check the plots: if the fingers are not moving, then the PID gains are most likely not up to the task; e.g., see [here](https://github.com/icub-tech-iit/ergocub-design-lowerarm/issues/245#issuecomment-2095469706).
```

2024-05-15 13:48 UTC, pattacini commented on src/tools/ergocub-fingers-tuning/scripts/init_ws.m
> +% All Rights Reserved.
```suggestion
% All Rights Reserved.
% Authors: simeone.dussoni@iit.it
%
```

2024-05-16 06:22 UTC, pattacini approved these changes
I've just merged my suggested edits straight away.
Fine with me 👍🏻 

Awaiting @mfussi66's review.

2024-05-16 09:23 UTC, mfussi66 requested changes
Thanks for the PR! 
I suggest the following to avoid putting too many files:
- remove all the .csv files that are not actually used for the tuning
- remove the pdf files, looking at the live script and launching it should be sufficient
- very minor, maybe replace the .mat files with simple text files?

2024-05-16 14:45 UTC, simeonedussoni commented
I left only the most useful  couple of matlab files to save the values of Kp,Ki and Kd for the fingers.
Also, I comented the lines to produce the .m file and the .pdf report (an eye check can be done when running the livescript that the plots are ok and the step response also)

2024-06-07 09:30 UTC, mfussi66 commented
Apologies for the delay, thanks for the changes @simeonedussoni ! 

I opened the script and it works well, the only thing I would change is adding the `init_ws` call at the beginning of the live script.

2024-12-05 10:01 UTC, closed without merging