ergoCubEmotions module - stint 2
icub-tech-iit/ergocub-software pull request #87
Opened 2023-03-27 08:23 UTC by martinaxgloria

The module is now refactored and the images are stored in a context called `ergoCubEmotions` and installed by means of `yarp_install`. In this way, ResourceFinder finds and reads the configuration file which is installed in a YARP's installation dir.

2023-03-28 06:51 UTC, pattacini requested changes
Fantastic job @martinaxgloria 🚀 
I would only refine the documentation. Please, follow the hints a left inline.

2023-03-28 06:51 UTC, pattacini commented on src/modules/ergoCubEmotions/ergoCubEmotions.xml
This documentation needs to be adapted to the new module 😉

2023-03-28 06:51 UTC, pattacini commented on src/modules/ergoCubEmotions/idl.thrift
You may consider documenting the API using the javadoc, which si recognized by doxygen.
Get inspired for this from the original code.

2023-03-28 06:52 UTC, pattacini commented on src/modules/ergoCubEmotions/ergoCubEmotions.xml
Read carefully the content of the file for this.

2023-03-28 08:14 UTC, martinaxgloria commented on src/modules/ergoCubEmotions/idl.thrift
Then simply by hand. I thought that it was an automatic way to generate those comments.
Ok, thanks @pattacini!

2023-03-28 08:16 UTC, pattacini commented on src/modules/ergoCubEmotions/idl.thrift
The other way around: those comments will be used at a second stage by doxygen to generate the online documentation. For the latter step, hold on; just focus on inserting the javadoc comments inline.

2023-03-28 08:44 UTC, pattacini requested changes
Just a minor fix.

2023-03-28 08:53 UTC, pattacini approved these changes

2023-03-29 07:56 UTC, Nicogene approved these changes

2023-03-29 07:56 UTC, merged

2023-03-29 07:56 UTC, Nicogene commented
Merged, thanks!